id: yahoo-news
version: 1
matches:
  - "https://news.yahoo.com/*"
description: "Yahoo News"
fetchMode: dom
content:
  item: "article, li.js-stream-content"
  id:
    selector: "a"
    attribute: "href"
  title:
    selector: "h1, h2, h3"
  url:
    selector: "a"
    attribute: "href"
  author:
    selector: "[rel='author']"
  body:
    selector: "p"
  image:
    selector: "article img"
    attribute: "src"
