id: cnn
version: 1
matches:
  - "https://www.cnn.com/*"
  - "https://cnn.com/*"
description: "CNN news"
fetchMode: dom
content:
  item: "article, .card"
  id:
    selector: "a"
    attribute: "href"
  title:
    selector: "h1, h2, h3"
  url:
    selector: "a"
    attribute: "href"
  author:
    selector: "[rel='author'], .byline__name"
  body:
    selector: "p"
  image:
    selector: "article img"
    attribute: "src"
