id: simonwillison
version: 1
matches:
  - "https://simonwillison.net/*"
description: "Simon Willison blog"
fetchMode: dom
content:
  item: "article"
  id:
    selector: "a"
    attribute: "href"
  title:
    selector: "h1, h2"
  url:
    selector: "a"
    attribute: "href"
  author:
    selector: "[rel='author'], .byline"
  body:
    selector: "p"
  image:
    selector: "article img"
    attribute: "src"
