id: google-news
version: 1
matches:
  - "https://news.google.com/*"
description: "Google News aggregation"
fetchMode: tab-dom
content:
  item: "article, c-wiz a[href*='./stories/']"
  id:
    selector: "a"
    attribute: "href"
  title:
    selector: "h3, h4"
  url:
    selector: "a"
    attribute: "href"
  author:
    selector: "span"
  body:
    selector: "span"
  image:
    selector: "img"
    attribute: "src"
